version: 2

before:
  hooks:
    - go mod download
    - mkdir -p .bin
    - env GOBIN={{ .Env.PWD }}/.bin go install braces.dev/errtrace/cmd/errtrace
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      # - arm64
    flags:
      - -toolexec={{ .Env.PWD }}/.bin/errtrace
      - -tags=containers_image_openpgp,exclude_graphdriver_btrfs,exclude_graphdriver_devicemapper
archives:
  # Optional: This makes the extracted binary strictly named 'lsw'
  # instead of 'lsw_0.1.0-pre1_linux_amd64'
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
