# Fedora was deliberately chosen to have a more recent version of Wine than Debian.

# The last version of powershell that is working with wine is: https://github.com/PowerShell/PowerShell/releases/tag/v6.2.5
ARG POWERSHELL_VERSION="6.2.5"
ARG XMAKE_VERSION="3.0.6" # https://github.com/xmake-io/xmake/releases/download/v3.0.6/xmake-v3.0.6.win64.zip
ARG CMAKE_VERSION="4.3.2"
ARG GIT_VERSION="2.52.0"
ARG SEVENZIP_VERSION="2501"

ARG WINEPREFIX=/opt/prefix

# =========================================================
# Stage 1: Populate wine prefix with tools
# =========================================================
FROM fedora:43 AS msvc-builder
LABEL lsw-image="true"

ARG WINEPREFIX
ARG POWERSHELL_VERSION
ARG XMAKE_VERSION
ARG CMAKE_VERSION
ARG GIT_VERSION
ARG SEVENZIP_VERSION

COPY wine-add-path.sh /usr/bin/wine-add-path
RUN chmod +x /usr/bin/wine-add-path

# ---- System dependencies (build-time) ----
RUN dnf install -y \
    wine \
    wine-core \
    wine-common \
    msitools \
    python3 \
    cabextract \
    p7zip \
    p7zip-plugins \
    xz \
    git \
    ca-certificates \
    findutils \
    procps-ng \
    xorg-x11-server-Xvfb \
    && dnf clean all

# ---- Wine configuration ----
ENV WINEPREFIX=${WINEPREFIX}
ENV WINEDEBUG=-all
ENV WINEDLLOVERRIDES=mscoree,mshtml=

RUN mkdir -p ${WINEPREFIX}

# Init wine
RUN wineboot --init && \
    wine reg add "HKCU\\Software\\Wine\\Version" /v "CurrentVersion" /d "10.0" /f && \
    wine reg add "HKCU\\Software\\Wine\\Version" /v "CurrentBuild" /d "19041" /f && \
    while pgrep wineserver > /dev/null; do sleep 1; done

# Install dotnet 4.8
RUN curl -L -o /usr/bin/winetricks https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks && \
    chmod +x /usr/bin/winetricks && \
    echo "Installing .NET 4.8 (This will take a few minutes)..." && \
    WINETRICKS_SUPER_QUIET=1 xvfb-run -a winetricks -q dotnet48 && \
    wineserver -w

WORKDIR /tmp
RUN git clone https://github.com/mstorsjo/msvc-wine
WORKDIR /tmp/msvc-wine

# Download + install MSVC inside the prefix
RUN mkdir -p "${WINEPREFIX}/drive_c/Program Files/MSVC"
RUN python3 vsdownload.py --accept-license --dest "${WINEPREFIX}/drive_c/Program Files/MSVC" && \
    ./install.sh "${WINEPREFIX}/drive_c/Program Files/MSVC"

# Configue msvc environment
COPY vswhere.c ./vswhere.c
COPY setup-msvc.sh ./setup-msvc.sh
RUN chmod +x ./setup-msvc.sh && ./setup-msvc.sh


# Install powershell
RUN curl -L -o /tmp/powershell.zip https://github.com/PowerShell/PowerShell/releases/download/v${POWERSHELL_VERSION}/PowerShell-${POWERSHELL_VERSION}-win-x64.zip
RUN mkdir -p "${WINEPREFIX}/drive_c/Program Files/Powershell/6"
RUN unzip /tmp/powershell.zip -d "${WINEPREFIX}/drive_c/Program Files/Powershell/6" || [ $? -eq 1 ]
RUN wine-add-path "C:\Program Files\Powershell\6"
RUN wineserver -w
RUN echo 'if (Get-Module -Name PSReadLine) { Remove-Module -Name PSReadLine }' > "${WINEPREFIX}/drive_c/Program Files/Powershell/6/profile.ps1"

# Install CMake
RUN curl -L -o /tmp/cmake.zip https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-windows-x86_64.zip
RUN 7z x /tmp/cmake.zip -o/tmp/cmake
RUN mv "/tmp/cmake/cmake-${CMAKE_VERSION}-windows-x86_64" "${WINEPREFIX}/drive_c/Program Files/CMake"
RUN wine-add-path "C:\Program Files\CMake\bin"
RUN wineserver -w

# Install xmake
RUN curl -L -o /tmp/xmake.zip https://github.com/xmake-io/xmake/releases/download/v${XMAKE_VERSION}/xmake-v${XMAKE_VERSION}.win64.zip
RUN 7z x /tmp/xmake.zip -o/tmp/xmake
RUN cp -r /tmp/xmake/xmake/ "${WINEPREFIX}/drive_c/Program Files/Xmake"
RUN wine reg add 'HKEY_CURRENT_USER\Environment' /v XMAKE_PROGRAM_DIR /t REG_SZ /d 'C:\Program Files\Xmake' /f
RUN wine-add-path "C:\Program Files\Xmake"
RUN wineserver -w

# Install git
RUN curl -L -o /tmp/git.7z https://github.com/git-for-windows/git/releases/download/v${GIT_VERSION}.windows.1/PortableGit-${GIT_VERSION}-64-bit.7z.exe
RUN mkdir -p "${WINEPREFIX}/drive_c/Program Files/Git"
RUN 7z x /tmp/git.7z -o"${WINEPREFIX}/drive_c/Program Files/Git"
RUN wine-add-path "C:\Program Files\Git\bin"

# Install 7z
RUN curl -L -o /tmp/7z.7z https://www.7-zip.org/a/7z${SEVENZIP_VERSION}-extra.7z
RUN 7z x /tmp/7z.7z -o"${WINEPREFIX}/drive_c/Program Files/7-Zip"
RUN mv "${WINEPREFIX}/drive_c/Program Files/7-Zip/7za.exe" "${WINEPREFIX}/drive_c/Program Files/7-Zip/7z.exe"
RUN wine-add-path "C:\Program Files\7-Zip"

# Install rustup
# Pin to rustup 1.28.2 which is known to work in Wine
# RUN curl -L -o /tmp/rustup-init.exe https://win.rustup.rs/x86_64
RUN curl -L -o /tmp/rustup-init.exe https://static.rust-lang.org/rustup/archive/1.28.2/x86_64-pc-windows-msvc/rustup-init.exe
RUN wine Z:/tmp/rustup-init.exe -vy
RUN wine rustup set auto-self-update disable
RUN wineserver -w

# =========================================================
# Stage 2: Minimal RootFS Builder
# =========================================================
FROM fedora:43 AS rootfs-builder
LABEL lsw-image="true"

# Create a directory to hold a minimal OS
RUN mkdir -p /mnt/rootfs

# Install strictly necessary dependencies into /mnt/rootfs
RUN dnf install -y \
    --installroot=/mnt/rootfs \
    --releasever=43 \
    --setopt=install_weak_deps=False \
    --setopt=tsflags=nodocs \
    --use-host-config \
    wine-core \
    wine-common \
    glibc-langpack-en \
    # Disable for now
    # bash \
    # coreutils \
    # grep \
    # sed \
    && dnf clean all --installroot=/mnt/rootfs

# Clean up dnf metadata/cache to save space
RUN rm -rf /mnt/rootfs/var/cache/dnf /mnt/rootfs/var/log/dnf*

# =========================================================
# Stage 3: Distroless Final Image
# =========================================================
FROM scratch

ARG WINEPREFIX

# Copy the minimal Fedora root filesystem
COPY --from=rootfs-builder /mnt/rootfs/ /

# Copy the populated Wine Prefix from the builder
COPY --from=msvc-builder ${WINEPREFIX} ${WINEPREFIX}

# Configure Environment
ENV WINEPREFIX=${WINEPREFIX}
ENV WINEDEBUG=-all
# ENV WINEDEBUG=+loaddll
ENV XDG_RUNTIME_DIR=/tmp
ENV LANG=en_US.UTF-8

WORKDIR /work

# Default entrypoint
CMD ["wine", "cmd"]
